export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_DETAILS = 'GET_POSTS_DETAILS';
export const PEGA_LISTA_CATEGORIAS = 'PEGA_LISTA_CATEGORIAS';
export const FILTERED_LIST = 'FILTERED_LIST';
export const FILTERED_LIST_REMOVE = 'FILTERED_LIST_REMOVE';
export const CLEAN_FILTER = 'CLEAN_FILTER';
export const ADICIONA_AO_CARRINHO = 'ADICIONA_AO_CARRINHO';